### ISSUE TITLE
[Main] テンプレートフォルダ内アセットの改変を検知する機能の実装

### ISSUE THREAD

**Issue by Kozu-vr** [vkettools/VitDeck#10]

**Comment by sokuhatiku** [comment]
- [x] 保護対象の登録、解除
- [x] 保護対象への編集を取り消し
- [ ] 保護対象の削除を取り消し
- [ ] 保護対象の移動を取り消し
- [ ] 保護対象フォルダ内への移動を取り消し
- [ ] 保護対象フォルダ内への新規作成を取り消し
- [ ] 操作キャンセルをユーザーに通知するUI

**Comment by sokuhatiku** [comment]
保護フォルダ内へのアセットの新規作成を禁止する機能の課題
- UnityEditor標準の検出機能（`AssetModificationProcessor.OnWillCreateAsset()`）ではアセットの作成を拒否することは出来ない
  - 他（移動、編集、削除）は拒否できる
- 上記関数内でマークしたものを`EditorApplication.Update`で削除することは出来る
  - この挙動のテストは難しい
- 作成されたものを削除して本当にいいのか？利用者の大事なアセットが消失したりしないか？

**Comment by Kozu-vr** [comment]
@sokuhatiku 
基本的にこの機能はベストエフォートの保護機能だと思っていて、ユーザーアセットが追加されることによる弊害はほとんどないと思っています。
実装が難しいようならアセットが作成されること関しては無視するでもよいかと思います。

**Comment by sokuhatiku** [comment]
@Kozu-vr そうですね。作成自体の検出は可能なので、警告位にとどめておきます。ありがとうございます。

**Comment by sokuhatiku** [comment]
作成を制限しない場合、一度作成したアセットが削除出来なくなってしまう
→削除も警告にとどめておくべき、編集のみ禁止？
→編集禁止ラベルを付けたアセットのみ編集、削除を禁止するとか？

**Comment by sokuhatiku** [comment]
ラベル管理にして、特定ラベルが付いたオブジェクトの削除、改変を禁止する形でも良さそう

**Comment by Kozu-vr** [comment]
@sokuhatiku 
ラベル良いですね！
独自テンプレート作成者も設定しやすくてよさそう。
ラベル方式に決定する場合はラベル名を先に決めてほしいです。（`VitDeck.Protect`とかですかね？）

**Comment by sokuhatiku** [comment]
@Kozu-vr 今検証中ですが、上手く行きそうなのでラベル式になるかと思います。
ラベル名は仮で`VitDeck.ReadOnly`という形にしているのですが、もし異存なければこのまま決定してしまってもよいと思います。

**Comment by Kozu-vr** [comment]
@sokuhatiku `VitDeck.ReadOnly`了解です！ こちらテンプレートにも付与します。

**Comment by sokuhatiku** [comment]
編集がセーブされなかったとき、プレハブ等のアセットは変更を破棄する手段が無いので、ダイアログ上で変更を破棄することが出来ると良い？

**Comment by sokuhatiku** [comment]
破棄するかどうか選択する機能の作成、及び、ラベルが付いているオブジェクトにHideFlags.NotEditableを付けることでそもそも普通の編集はできないようにしました。

編集禁止のほうは実装しましたが、現在変更破棄の方がPrefabやシーンでうまく動いていないので修正方法を検討中です。

**Comment by sokuhatiku** [comment]
MaterialやScriptableObjectは`Resources.UnloadAsset()`で保存されていない変更点を破棄可能。
SceneやPrefab(GameObject)は上記関数ではエラーになる模様。

**Comment by sokuhatiku** [comment]
- AssetModificationProcessorでアセットの複製を検出できない。
- 複製時ラベルはコピーされる→削除や移動が保護される。
- 複製時HideFlagsがコピーされたりされなかったりする。
誤って複製した際にユーザーによっては詰んでしまうのでなんとかしたいが……

**Comment by sokuhatiku** [comment]
ここに載っているコードを応用すればhierarchy及びprojectビューで色々なコマンドが取得できる模様。
https://answers.unity.com/questions/1274030/unity-duplicate-event.html

**Comment by Kozu-vr** [comment]
Wikiに使用する為、関連するIssueに画像コメントしています。
![image](https://user-images.githubusercontent.com/46106857/57583183-ff01b180-7508-11e9-8c03-bdfdaf99a0dd.png)

**Comment by Kozu-vr** [comment]
アセット別のチェックをToDoと#29に課題を分離しました。
こちらはクローズします。
