### ISSUE TITLE
テンプレートに空フォルダを入れる方法の検討

### ISSUE THREAD

**Issue by Kozu-vr** [vkettools/VitDeck#23]
#19 #22 より、テンプレートに空フォルダを入れた構成にしてそれを複製することは十分考えられるが.unitypackageのエクスポートでは空フォルダを含めることができない。
そのため何らかの追加の処置が必要になる。
実現方法を検討する。

**Comment by Kozu-vr** [comment]
実装アイデア１：`VitDeck.dummy`のようなラベルを付けたダミーファイルを入れておいてテンプレートコピー時にそれらを無視する。

**Comment by Kozu-vr** [comment]
複製の実装方針として以下のどちらを採用するか。
1. template asset内のアセットを丸ごとコピーして、コピー後のアセットに対してリネームや不要ファイル削除を行う
2. template asset内のアセットを１つずつ確認しながらコピー＆リネーム、不要ファイルのスキップを行う

**Comment by Kozu-vr** [comment]
1の場合、template asset直下に複数アセットがある場合はそれらをすべてコピーする必要があって結局2に近い処理を行う必要がある。

2を下記手順で行うのがよさそう。
- コピーする全アセットのパスをリスト化（このタイミングで無視するアセットは除外）
- それぞれに対するコピー先のパスを置換・生成
- すべてのアセットについてコピー実行

**Comment by Kozu-vr** [comment]
実装アイデア２：
空フォルダの追加場所をTemplatePropetyで指定しておいてコピー後に空フォルダを生成する。

１に比べ指定が煩雑に感じるためあまり良い実装に思えない。

**Comment by Kozu-vr** [comment]
実装アイデア3：
アイデア１のラベルの代わりにファイル名で無視する。
`VitDeck_ignore`のような特定ファイル名は無視。

ラベルを付けなくても良くなるがファイル変更検知用に既にReadOnlyラベル指定という概念があるため、かえって煩雑？

**Comment by Kozu-vr** [comment]
実装アイデア4：
空フォルダーを表すscriptableObjectの.assetファイルを定義し、テンプレート内の空フォルダを生成したい位置に作成しておく。
テンプレートコピー時に該当`.asset`ファイルの代わりに同名の空フォルダを生成する。

作成者はCreateメニューから空フォルダオブジェクトを作っておくだけでよいので比較的楽に思える。

**Comment by Kozu-vr** [comment]
アイデア１かアイデア４のどちらかだと思うのですが意見欲しいです。

**Comment by sokuhatiku** [comment]
個人的には1が実装が楽そうでいいと思います。

**Comment by Kozu-vr** [comment]
@sokuhatiku 
ソクハさんのをアイデア5とすると
作成手順は
1. 空フォルダを作る。
2. 空フォルダ内に`VitDeckDummy`のようなScriptableObjectの`.asset`を作成。

コピー処理は対象リスト作成時にアセットの種類を見て`VitDeckDummy`だったら無視する感じですよね。

ダミー用に何を作るか未定義のアイデア１より良さそうです。
アイデア4を見返すと「コピー時に変化する代替物」という普段使わない概念が増えるので覚える負荷が高くてあまりよくないかもしれないですね。

明日もう一度見てアイデア５より良いアイデアが無ければ５の方針で行きたいと思います。
