### ISSUE TITLE
テンプレートを追加/削除した時のGUIの挙動が不安定

### ISSUE THREAD

**Issue by Kozu-vr** [vkettools/VitDeck#32]
#30 より
再コンパイルを伴わない（スクリプトを含まない）テンプレートを追加/削除した時のGUIの挙動が不安定にみえる。

可能であれば改善したい。

**Comment by sokuhatiku** [comment]
これ調べてみます。

**Comment by sokuhatiku** [comment]
調査結果：
- Issue作成当時の不安定さは見られなかった。
- ただし以下の現象を確認
  1. スクリプト無しのテンプレートを追加/削除した時にテンプレートリストが更新されない。
  1. スクリプト有りのテンプレートを追加/削除した時にテンプレートリストのサイズが0になる。

TemplateLoaderを頻繁に操作することは無いので、押された時に`Init()`を呼び出すRefreshボタンを追加するだけで良さそう？

iiに関してはテンプレートに限らず何らかのスクリプトの追加/削除、Editorの再起動時など頻繁に発生するので修正した方がいい？（修正自体は可能）

**Comment by Kozu-vr** [comment]
@sokuhatiku 調査ありがとうございます
＞テンプレートRefreshボタン 
おっしゃる通りテンプレートの追加は運営以外は基本考えなくてよい操作だと思うのでボタンを増やすより再度ウインドウを開きなおしてという方がシンプルになってよいかも。いかがでしょうか。
＞再コンパイル時の挙動
全体的に再コンパイルに対する対処がうまく設計できてない気がしていて、よい修正アイデアがあればぜひ修正お願いしたいです。

**Comment by sokuhatiku** [comment]
@Kozu-vr 了解です。
ではここに関しては再コンパイル時の対処のみ追加する方針で修正しようと思います。

**Comment by Kozu-vr** [comment]
以下は再コンパイル時に初期化されるのがOKとする。
- 選択中の項目
- ライセンス条文のスクロール位置
- 置き換え文字列に入力した内容
