### ISSUE TITLE
アップデート確認先URLの持ち方をgithubリポジトリ以外でも持ちやすくしたい。

### ISSUE THREAD

**Issue by Kozu-vr** [vkettools/VitDeck#44]
#9 より
https://github.com/vkettools/VitDeck/issues/9#issuecomment-493381744

このようなjsonを別サーバーにアップする場合に今の`Repository`の持ち方では対応できないので、もう少し緩い持ち方にできないか検討したい。

**Comment by sktkkoo** [comment]
@Kozu-vr 
GitHubになるべく依存しないようにするなら、必要な情報はすべてjsonファイルにまとめて、そこですべて管理するのがいいように思います。とりあえず、jsonファイルを取得するurl先を指定できるように変更して、現在、以下のようになっているjsonファイルの中身を、
~~~
{
"tag_name": "0.0.0"
}
~~~
例えば、次のように変更する予定です。
~~~
{
  "tag_name": "v0.0.0-alpha",
  "version": "0.0.0",
  "package_name": "VitDeck-v0.0.0-alpha.unitypackage",
  "download_url": "https://github.com/vkettools/VitDeck/releases/download/v0.0.0-alpha/VitDeck-v0.0.0-alpha.unitypackage"
}
~~~

ご意見、ご指摘あればお願いします。

**Comment by Kozu-vr** [comment]
確かに、当初はGitHub APIと互換性を持たせることを考えていましたが独自形式でよい気がしてきました。
このフォーマットの場合、tag_nameが処理内で使われる場所はどこになりますか？
他は問題ないと思います。

**Comment by sktkkoo** [comment]
ありがとうございます。確かに、ほかの情報があればtag_nameは不要なので削除しておきます。
