### ISSUE TITLE
VitDeckの各機能を呼び出す機能の名称について

### ISSUE THREAD

**Issue by sokuhatiku** [vkettools/VitDeck#5]
#4 にて

VitDeckのルート名前空間に置くつもりだったアセンブリがあるが、一つ階層を掘ったほうが各機能と階層が並んで綺麗になるため、階層を掘るために名前を与えたい。

**Comment by sokuhatiku** [comment]
@Kozu-vr 🙏

**Comment by sokuhatiku** [comment]
まずこれの責務に関して認識共有がしたいです。

こちらの認識ですが、このCore(仮)がやる事は各機能の呼び出しです。
（例：Export操作をCore(仮)が受けた場合、Validatorでの検証をした後にExporterを使って出力する）

**Comment by sokuhatiku** [comment]
例をより深堀りしてみると、こんな感じですね

1. `Core.GUI` Export Boothが選択される
1. `Core` Validatorを起動する
1. `Validator` ブースを検証する
1. `Core` 検証が通った場合、Exporterを起動する。
1. `Exporter` ブースの出力を行う
1. `Core` プレビューを行う場合はプレビュー用の機能を起動する

**Comment by Kozu-vr** [comment]
> こちらの認識ですが、このCore(仮)がやる事は各機能の呼び出しです。
> （例：Export操作をCore(仮)が受けた場合、Validatorでの検証をした後にExporterを使って出力する）
そこの認識がちょっと違ってたみたいです。
アップデート通知など全体にかかる機能（他アセンブリを参照する必要がないもの）が`VitDeck`に入っているのが気になったので
VitDeckに入れるつもりだった機能のうちGUIを持っていたり他のアセンブリを参照する必要のないものをCoreとして分けて、各機能の呼び出しは今のままVitDeck空間にあるイメージでした。
承前：https://github.com/vkettools/VitDeck/pull/4#issuecomment-487446665


なので、上の例の場合、こちらはこのフローを想定してました。
> 1. `Core.GUI` Export Boothが選択される（`Core`のRunExportのようなメソッドで以下2.～6.を実行）
> 2. `VitDeck` Validatorを起動する
> 3. `Validator` ブースを検証する
> 4. `VitDeck` 検証が通った場合、Exporterを起動する。
> 5. `Exporter` ブースの出力を行う
> 6. `VitDeck` プレビューを行う場合はプレビュー用の機能を起動する

**Comment by Kozu-vr** [comment]
1. 責務についてまず`Core`はツールアップデート機能などの他アセンブリを参照しない基本機能を受け持つ想定していました。
2. 各機能の呼び出しはVitDeckの全体にかかることなので`VitDeck`空間に持たせたい。

今の認識とやりたかったことはこれです。
GUIを`Core`にいれつつ2. を実現させるには`VitDeck`空間にRunExporterやRunValidatorメソッドを実装すれば行けそう？

1. `Core.GUI` Export Boothが選択される
2. `Core` Export Boothが実行(VitDeck空間の`RunExporter`の実行)
3. `VitDeck`RunExporterメソッドから`VitDeck`RunValidatorメソッドでValidator起動、ブースを検証
4. `VitDeck`RunExporterメソッドでExporter起動
5. `Exporter` ブースの出力を行う
6. `VitDeck` プレビューを行う場合はプレビュー用の機能を起動する

**Comment by Kozu-vr** [comment]
コマンドラインからは`VitDeck`のRunExporter等を直接実行するイメージ。
Core.GUI,Coreのやってる事はそれを実行するためのボタンに過ぎない感じです。

**Comment by sokuhatiku** [comment]
アップデートなど、名前を付けられる機能に関しては開発に入ったタイミングで（もしくは開発が進み、これCoreがやる事じゃないなと思った時点で）新しくフォルダ、アセンブリを作って単一の機能として切り出す想定でした。

他機能を呼び出すものをVitDeck空間に入れておくことは良いと思います。
ただ、CoreにVitDeck空間に対する参照を入れてしまうと、芋づる式にCoreから他所への参照が発生してしまうのではないか？と思います。VitDeck.GUIを用意してそこからVitDeckの機能を呼び出した方が奇麗ではないでしょうか？（今の形にほぼ戻ってしまいますが）

**Comment by Kozu-vr** [comment]
そうかそこの参照は切れないのか。
@sokuhatiku の言うように機能呼び出しGUI部分については`VitDeck.GUI`とするのが良いの理解しました。Coreに関しては無しの方向で行きましょう。
単一機能切り出す想定もその方向で考えるようにします。こちら確認の上クローズお願いします。

**Comment by sokuhatiku** [comment]
あ、ただし、フォルダ一つ掘ったほうが綺麗というのはその通りなので、VitDeck名前空間においてあるやつに何らかの名前を付けて一段下げてしまうのは大いにアリだと考えています。こちらいかがでしょう？

**Comment by Kozu-vr** [comment]
この機能しか入れない前提で`VitDeck.Runcher` とかどうでしょう？

**Comment by sokuhatiku** [comment]
`Launcher` もしくは`Rancher`ですかね？
とりあえず他にもパッと浮かんだやつを並べてみます。
- `Main`
- `Front`
- `General`
- `Pipeline`
- `Orchestration`
- `Wizard`
- `Runner`

**Comment by Kozu-vr** [comment]
これは恥ずかしい・・・
`Launcher`（ランチャー）ですね。

- `Terminal`

もありえそう。

@sokuhatiku 的ベストはどれ？

**Comment by sokuhatiku** [comment]
色んな所に参照を持つ奴の受け皿になると思うので、`Main`あたりの主語がでかいやつを推したいですね。

**Comment by Kozu-vr** [comment]
OKです、他を推す強い理由はないので `Main`で決定しましょう！

**Comment by sokuhatiku** [comment]
了解です。それでは暫定`Main`でクローズします。ありがとうございました！
