### ISSUE TITLE
ランチャー作成

### ISSUE THREAD

**Issue by sokuhatiku** [vkettools/VitDeck#6]
UnityのメニューバーからGUI操作で呼び出せる、VitDeckのエントランス的なGUIと各機能の呼び出し動作のベースが必要

#  基本仕様
（想定です。追記修正あればツッコミをお願いします。）

- Unityのメニューバー上にVitDeckの項目がある。
- クリックしてプルダウンメニューから出展者がやりたいことを選ぶ。
- 選ばれた項目をVitDeck.Main内で各機能を呼び出すことで実行する。

**Comment by sokuhatiku** [comment]
基本仕様（想定。追記修正あればツッコミをお願いします。）
- Unityのメニューバー上にVitDeckの項目がある。
- クリックしてプルダウンメニューからLauncherを開くとLauncherウィンドウが開く。
- Launcherウィンドウ上のボタンから各機能の呼び出しが可能。

**Comment by Kozu-vr** [comment]
イメージしてたのはVitDeckのメニューバーのサブアイテムとして各機能が並んでる感じだったけどどちらが良いだろう。

[VitDeck]
  - Template loader
  - Booth checker
  - Booth exporter

**Comment by sokuhatiku** [comment]
そちらの方がお手軽ですね。一旦そっちにしましょうか

**Comment by Kozu-vr** [comment]
もしLauncherにバージョン番号とか手動アップデートチェックのような機能を入れたくなった場合は about みたいなダイアログを出すようにするのが良い気がします。

**Comment by sokuhatiku** [comment]
一つ押さえておきたい箇所ですが、出展者がやりたい事があって、それを叶えるためのメニュー及びVitDeckだという事は忘れないでおく必要がありそうです。（自戒）

**Comment by Kozu-vr** [comment]
設計レビュー時に利用者の作業フローの確認を忘れないようにしましょう！

**Comment by sokuhatiku** [comment]
なるべくGUIをプレゼンターとして扱うフローの試作
https://gist.github.com/sokuhatiku/d3063a9b916414196b316f9e0f943131
1. Main.GUI.MainMenuGUIでプルダウンから選択
1. Main.Infoがイベントを発行
1. Main.GUI.InfoGUIがイベントを受けてウィンドウを描画

Infoならここまで複雑にする必要はなさそうだけど、ExportPackage時にValidatorとExporterを連携させる場合はこうした方が楽になりそう。

**Comment by Kozu-vr** [comment]
ざっとみた感じで分け方はとても良さそうに見えます！

https://anchan828.github.io/editor-manual/web/callbacks.html#h13-3
> 注意したいのはエディター上でゲームを再生した直後にも InitializeOnLoad 属性の付いた静的コンストラクタが呼び出されてしまいます。

試せて無いですがInitializeOnLoadMethod属性は大丈夫かちょっと気になってます。

2019年4月30日(火) 17:36 Sokuhatiku <notifications@github.com>:
