### ISSUE TITLE
[Main]アップデート確認機能の実装

### ISSUE THREAD

**Issue by Kozu-vr** [vkettools/VitDeck#9]
新しいリリースがある場合、アップデートを促す通知とDL更新する機能を実装する。

**Comment by sktkkoo** [comment]
必要な機能（ソクハさんのアイデアを参考に）
- [ ] UnityWebRequestでGitHub APIで最新リリース情報取得
- [ ] リリース情報のJSONをパースしてVersion情報を取得
- [ ] ローカルのVersionと比較してUpdate可能かチェック
- [ ] Versionが最新と異なっている場合はUpdateの案内を表示
- [ ] Updateボタンでダウンロード
- [ ] ダウンロードしたUnityPackageをAssetDatabase.ImportPackage() で自動でインポート

**Comment by sktkkoo** [comment]
課題
- GitHub APIを使っているが、利用制限があるので問題ないか確認が必要
  - 1時間60件まで
  - 取得できる情報はpublicな情報のみ (privateリポジトリの情報は取得できない)
  - どうしても制限をなくしたい場合は認証が必要
- tagからVersion情報を取ってきているため、tag名の付け方を整合しておく必要がある
  - 現在の実装だと"v1.0.0"のような形式
- 案内表示の検討
  - 現状はとりあえずInfoWindow.csの一部を改変（ UpdateチェックがInfoメニューからというのはわかりにくい？）

**Comment by sktkkoo** [comment]
現状のイメージ
- Versionが最新の場合
![bandicam 2019-05-15 23-07-30-766](https://user-images.githubusercontent.com/6031376/57782035-5f415f00-7766-11e9-94da-f470da371c54.jpg)
- Versionが最新でない場合
![bandicam 2019-05-15 22-53-55-561](https://user-images.githubusercontent.com/6031376/57781673-9d8a4e80-7765-11e9-918c-c750862b1dc6.jpg)

**Comment by Kozu-vr** [comment]
> * GitHub APIを使っているが、利用制限があるので問題ないか確認が必要
>   * 1時間60件まで
>   * 取得できる情報はpublicな情報のみ (privateリポジトリの情報は取得できない)
>   * どうしても制限をなくしたい場合は認証が必要

→ １時間６０は他の用途でも消費されてた気がするので、アップデート情報取得先を手動配置したGitHub API相当の情報を含むJSONファイルにしても良い気がします。
テストも正式版のリリースを使うのは大変だと思うので公開時のファイル配置を考えてみます。

> * tagからVersion情報を取ってきているため、tag名の付け方を整合しておく必要がある
>   
>   * 現在の実装だと"v1.0.0"のような形式

→ リリース日付からtagを新旧でソート→バージョン名を取得するような処理は難しい？

> * 案内表示の検討
>   * 現状はとりあえずInfoWindow.csの一部を改変（ UpdateチェックがInfoメニューからというのはわかりにくい？）

→ 案内通知で以下が実現できるとほとんどのユーザーは問題ない気がしています。
「更新しますか（後でInfoウインドウから更新することもできます）：Yes」を押す→Infoウインドウを開く

**Comment by Kozu-vr** [comment]
updateボタンを押すと手動更新チェックが実行されるイメージであってますか？

**Comment by Kozu-vr** [comment]
あ、そうかチェックはWindow開く時点で終わってるのか。
最新の場合はボタン非活性で「最新のバージョンです」という表示があると嬉しいかも。

**Comment by sktkkoo** [comment]
表示、了解しました！
メニューを開くたびに毎回更新チェックだとやや煩雑なので、ボタンで手動チェックでもいいかもですね。どのくらいの頻度で使いそうかにもよる気がしますが。

**Comment by Kozu-vr** [comment]
@sktkkoo 
ありがとうございます！
Infoダイアログを意識的に開くことは普通ないとおもいますし、ブラウザの更新と同じようにInfoダイアログ表示時にチェックされるだけで十分な気もしますね

**Comment by sktkkoo** [comment]
@Kozu-vr 
了解です！

残りの指摘ですが、JSONファイルを別途用意する件、承知しました。リリース時のtagとunitypackage名がわかればダウンロード先のリンクも求まるので、その二つの情報さえあればとりあえず大丈夫そうです。

tag名については、”ver1.0.0”なのか”1.0.0”なのか"v1.0.0"なのか決めておきたい、という趣旨でした。（毎回の名付け方に統一さえ取れていれば問題ないと思います）

**Comment by Kozu-vr** [comment]
> 残りの指摘ですが、JSONファイルを別途用意する件、承知しました。リリース時のtagとunitypackage名がわかればダウンロード先のリンクも求まるので、その二つの情報さえあればとりあえず大丈夫そうです。
> tag名については、”ver1.0.0”なのか”1.0.0”なのか"v1.0.0"なのか決めておきたい、という趣旨でした。（毎回の名付け方に統一さえ取れていれば問題ないと思います）

この部分ですが、タグ名とバージョン番号を必ず一致させておけば
Latestのタグ名がVitDeck内部で持ってるバージョン番号と同一かチェックするだけで最新か判定できるのでチェックにtag名の詳細は不要な構造になる？

**Comment by sktkkoo** [comment]
そうですね。いまも「tag名の先頭の"v"を取ったもの」と「内部のバージョン番号」が同一かチェックしているだけなので、大した手間ではないのですが、シンプルな方がバグを生みにくいように思います。

**Comment by Kozu-vr** [comment]
ではGitHubのリリースタグ付けはバージョンをそのままつけることにしますね

**Comment by Kozu-vr** [comment]
忘れてた、リリースファイル名はシンプルにVitDeck-タグ名.unitypackageにしたいと思います。
VitDeck-1.0.0.unitypackage

**Comment by Kozu-vr** [comment]
jsonファイルは最終的にgithub.ioのwebページのディレクトリを使って公開しようと思います。
以下にテスト用の同構成リポジトリを作りましたのでテスト時はそちらのjsonファイルを自由に修正してください。

VitDeckTestリポジトリの`gh-pagesブランチ/releases`に`latest.json`というフォルダを置いています。
https://github.com/vkettools/VitDeckTest/tree/gh-pages/releases

以下のURLにアクセスするとjsonファイルがDLできます。
https://vkettools.github.io/VitDeckTest/releases/latest.json

**Comment by sktkkoo** [comment]
ありがとうございます！

**Comment by sktkkoo** [comment]
追加作業
- [ ] リポジトリ名やownerなど変更可能性のない共通情報を一か所にまとめたい
- [ ] ダウンロード後のunitypackageの削除

**Comment by sktkkoo** [comment]
- [ ] ネットワーク未接続（またはネットワークエラー）の時の表示
![bandicam 2019-05-20 22-55-49-930](https://user-images.githubusercontent.com/6031376/58027161-fd606b00-7b52-11e9-9c56-957b3d7aa162.jpg)

**Comment by Kozu-vr** [comment]
こちら記載分はマージ完了の為Closeします。

**Comment by Kozu-vr** [comment]
Wiki用画像
![image](https://user-images.githubusercontent.com/46106857/58798699-411c9f80-863e-11e9-9f42-5de959da57af.png)
