### ISSUE TITLE
サブアセットを含むアセットの保護解除テストを見直す

### ISSUE THREAD

**Issue by sokuhatiku** [vkettools/VitDeck#94]
アセット保護解除時の処理は、アセットを作成して一括テスト→テストが落ちたら個別対応をしていたのですが、
#90 のように、スクリプトから生成するアセットとGUIで生成するアセットの構造が違ったために、テストは通るものの実際のアセットで問題が発生したため、アセット保護解除のテストを再度見直す必要があります。

**Comment by sokuhatiku** [comment]
今Restorerで個別対応しているアセット

- DefaultAsset
- GameObject(Prefab)
- AudioClip
- GameObject(ModelPrefab)
- Shader
- TextAsset
- LightingDataAsset
- SceneAsset
- AnimatorController

サブアセットを持つアセット

- AnimatorController
- VisualTreeAsset
- Texture2D(Sprite)
- AudioMixerController
- GameObject(Tree)
- GameObject(ModelPrefab)
- LightingDataAsset
- GameObject(ModelPrefab)
- GameObject(Prefab)

差分（サブアセットを持つが個別対応されていないアセット）

- AudioMixerController
- Texture2D(Sprite)
- VisualTreeAsset

これらのアセットの情報は以下の通り

IsMain | FileName | ObjectName | Type | HideFlags | HideFlags(Code)
-- | -- | -- | -- | -- | --
**MAIN** | Square.png | Square | UnityEngine.Texture2D | 0 | HideFlags.None
SUB | Square.png | Square | UnityEngine.Sprite | 0 | HideFlags.None
**MAIN** | New UXML.uxml | New UXML | UnityEngine.Experimental.UIElements.VisualTreeAsset | 0 | HideFlags.None
SUB | New UXML.uxml | inlineStyle | UnityEngine.StyleSheets.StyleSheet | 0 | HideFlags.None
**MAIN** | NewAudioMixer.mixer | NewAudioMixer | UnityEditor.Audio.AudioMixerController | 0 | HideFlags.None
SUB | NewAudioMixer.mixer | Master | UnityEditor.Audio.AudioMixerGroupController | 0 | HideFlags.None
SUB | NewAudioMixer.mixer | Snapshot | UnityEditor.Audio.AudioMixerSnapshotController | 0 | HideFlags.None
SUB | NewAudioMixer.mixer | Attenuation | UnityEditor.Audio.AudioMixerEffectController | 3 | HideFlags.HideInHierarchy \| HideFlags.HideInInspector
SUB | NewAudioMixer.mixer | Chorus | UnityEditor.Audio.AudioMixerEffectController | 3 | HideFlags.HideInHierarchy \| HideFlags.HideInInspector

この表を見ると、 **AudioMixerController** および **Texture2D(Sprite)** に関してはサブアセットとメインアセットが共に`HideFlags.None`のため対策は不要。残りは一つ。

- **AudioMixerController**

**Comment by sokuhatiku** [comment]
サブアセットを持たないがHideFlagsが`HideFlags.NotEditable`であり、対応が必要なアセット
優先度が低い為放置していたが、修正は容易なのでついでに直してしまいたい

IsMain | FileName | ObjectName | Type | HideFlags | HideFlags(Code)
-- | -- | -- | -- | -- | --
MAIN | NewComputeShader.compute | NewComputeShader | UnityEngine.ComputeShader | 8 | HideFlags.NotEditable
MAIN | Movie.mp4 | Movie | UnityEngine.Video.VideoClip | 8 | HideFlags.NotEditable
MAIN | New Avatar Mask.mask | New Avatar Mask | UnityEngine.AvatarMask | 8 | HideFlags.NotEditable

**Comment by Kozu-vr** [comment]
@sokuhatiku 調査ありがとうございます！
1.0.0-vketB_beta または 1.0.0-vketBのどちらかで取り込むのでdevelopからブランチして修正お願いできますか？

**Comment by sokuhatiku** [comment]
@Kozu-vr 了解しました！

**Comment by sokuhatiku** [comment]
サブアセットを持たないアセットのうち、AvatarMaskに関しては用意されたアセットと新規作成したアセットの状態が食い違っていた（新規作成版は`NotEditable`が付いていない）ので、新規作成した方に合わせておきました。

IsMain | FileName | ObjectName | Type | HideFlags | HideFlags(Code)
-- | -- | -- | -- | -- | --
MAIN| New Avatar Mask.mask| New Avatar Mask| UnityEngine.AvatarMask| None| 0

**Comment by Kozu-vr** [comment]
あれ、なんでだろう・・・ 後でデータの方、こちらでも確認してみます。
ありがとうございます！
